In [1]:
#Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix.
import numpy as np

# Create array from 1 to 10
arr = np.arange(1, 11)

# Reshape to 2x5 matrix
reshaped_arr = arr.reshape(2, 5)

print(reshaped_arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [3]:
#Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index.
# Create array from 1 to 20
arr = np.arange(1, 21)

# Extract elements from index 5 to 14 (15 is excluded)
extracted = arr[5:15]

print(extracted)

[ 6  7  8  9 10 11 12 13 14 15]


In [5]:
#Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. Then, add a new item to the series with the key 'pears' and the value 4.
import pandas as pd

# Create initial Series
fruits = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})

# Add new item
fruits['pears'] = 4

print(fruits)

apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [7]:
#Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data.

data = {
    'name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Ethan', 
             'Fiona', 'George', 'Hannah', 'Ian', 'Julia'],
    'age': [25, 30, 22, 28, 35, 24, 27, 26, 29, 31],
    'gender': ['Female', 'Male', 'Male', 'Female', 'Male', 
               'Female', 'Male', 'Female', 'Male', 'Female']
}

# Create DataFrame
df = pd.DataFrame(data)

print(df)

      name  age  gender
0    Alice   25  Female
1      Bob   30    Male
2  Charlie   22    Male
3    Diana   28  Female
4    Ethan   35    Male
5    Fiona   24  Female
6   George   27    Male
7   Hannah   26  Female
8      Ian   29    Male
9    Julia   31  Female


In [9]:
# Add 'occupation' column (repeating values to match 10 rows)
occupations = ['Programmer', 'Manager', 'Analyst'] * 3 + ['Programmer']  # Total 10 values
df['occupation'] = occupations

print(df)

      name  age  gender  occupation
0    Alice   25  Female  Programmer
1      Bob   30    Male     Manager
2  Charlie   22    Male     Analyst
3    Diana   28  Female  Programmer
4    Ethan   35    Male     Manager
5    Fiona   24  Female     Analyst
6   George   27    Male  Programmer
7   Hannah   26  Female     Manager
8      Ian   29    Male     Analyst
9    Julia   31  Female  Programmer


In [11]:
#Select the rows of the dataframe where the age is greater than or equal to 30.
age_filtered_df = df[df['age'] >= 30]

print(age_filtered_df)


    name  age  gender  occupation
1    Bob   30    Male     Manager
4  Ethan   35    Male     Manager
9  Julia   31  Female  Programmer


In [13]:
#Convert this dataframe to a csv file and read that csv file, finally display the contents.
df.to_csv('people_data.csv', index=False)


In [15]:
df_from_csv = pd.read_csv('people_data.csv')


In [17]:
print(df_from_csv)

      name  age  gender  occupation
0    Alice   25  Female  Programmer
1      Bob   30    Male     Manager
2  Charlie   22    Male     Analyst
3    Diana   28  Female  Programmer
4    Ethan   35    Male     Manager
5    Fiona   24  Female     Analyst
6   George   27    Male  Programmer
7   Hannah   26  Female     Manager
8      Ian   29    Male     Analyst
9    Julia   31  Female  Programmer
